/** Grimoire dark-fantasy theme for Clerk sign-in / sign-up. */
export const grimoireClerkAppearance = {
  variables: {
    colorBackground: '#12121a',
    colorInputBackground: '#1c1c28',
    colorInputText: '#e8e0d0',
    colorText: '#e8e0d0',
    colorTextSecondary: '#b8aea3',
    colorTextOnPrimaryBackground: '#0a0a0f',
    colorPrimary: '#c9a84c',
    colorDanger: '#d42b2b',
    colorSuccess: '#4ade80',
    colorWarning: '#fbbf24',
    colorBorder: '#2a2a3a',
    colorMuted: '#1c1c28',
    colorMutedForeground: '#b8aea3',
    colorNeutral: '#e8e0d0',
    colorShimmer: '#2a2a3a',
    borderRadius: '6px',
    fontFamily: 'Inter, sans-serif',
    fontSize: '14px',
  },
  elements: {
    rootBox: 'w-full',
    card: 'shadow-panel border border-[#2a2a3a] bg-[#12121a]',
    headerTitle: 'font-display tracking-wider text-[#e8e0d0]',
    headerSubtitle: 'text-[#b8aea3]',
    socialButtonsBlockButton:
      'border border-[#2a2a3a] bg-[#1c1c28] hover:bg-[#2a2a3a] transition-colors',
    socialButtonsBlockButtonText: 'text-[#e8e0d0] font-medium',
    socialButtonsProviderIcon: 'opacity-100',
    dividerLine: 'bg-[#2a2a3a]',
    dividerText: 'text-[#b8aea3]',
    formFieldLabel: 'text-[#e8e0d0]',
    formFieldInput:
      'text-[#e8e0d0] placeholder:text-[#8a8075] border-[#2a2a3a] bg-[#1c1c28]',
    formFieldInputShowPasswordButton: 'text-[#b8aea3]',
    formButtonPrimary:
      'bg-[#c9a84c] text-[#0a0a0f] hover:bg-[#dfc06a] font-semibold',
    formButtonReset: 'text-[#c9a84c] hover:text-[#dfc06a]',
    footerActionText: 'text-[#b8aea3]',
    footerActionLink: 'text-[#c9a84c] hover:text-[#dfc06a]',
    identityPreviewText: 'text-[#e8e0d0]',
    identityPreviewEditButton: 'text-[#c9a84c]',
    alternativeMethodsBlockButton: 'text-[#e8e0d0] border-[#2a2a3a]',
    otpCodeFieldInput: 'text-[#e8e0d0] border-[#2a2a3a]',
    formResendCodeLink: 'text-[#c9a84c]',
    alertText: 'text-[#e8e0d0]',
  },
} as const;
