-- AlterTable
ALTER TABLE "Scene" ADD COLUMN IF NOT EXISTS "timeOfDay" TEXT NOT NULL DEFAULT 'day';
ALTER TABLE "Scene" ADD COLUMN IF NOT EXISTS "gameTimeHour" INTEGER NOT NULL DEFAULT 12;
ALTER TABLE "Scene" ADD COLUMN IF NOT EXISTS "gameTimeMinute" INTEGER NOT NULL DEFAULT 0;
