/** Auto-generated by scripts/generate-spell-effects-catalog.mjs — do not edit by hand. */

import type { ActiveSpellEffect } from '@grimoire/shared';
import type { Jb2aEffectAsset } from './jb2aAssets';

export type SpellCastMode = 'aoe' | 'ranged' | 'self' | 'melee';

export interface CatalogJb2aAsset {
  basename: string;
  dpi: number;
  directed: boolean;
  variantKey: string;
  suffix: string;
  width: number;
  height: number;
  durationMs: number;
}

export interface SpellEffectCatalogEntry {
  id: string;
  name: string;
  castMode: SpellCastMode;
  embersType: 'CIRCLE' | 'CONE' | 'TARGET' | 'WALL';
  concentration: boolean;
  hasZoneLoop: boolean;
  /** Token clicks required on map (0 = none). */
  maxTargets: number;
  jb2a: CatalogJb2aAsset;
  aoe?: { size: number; type: string };
}

export const SPELL_EFFECTS_CATALOG: SpellEffectCatalogEntry[] = [
  {
    "id": "antilife_shell",
    "name": "Antilife Shell",
    "castMode": "aoe" as SpellCastMode,
    "embersType": "CIRCLE",
    "concentration": true,
    "hasZoneLoop": true,
    "maxTargets": 0,
    "jb2a": {
      "basename": "5th_Level/Antilife_Shell/AntilifeShell_01_Blue_Circle",
      "dpi": 100,
      "directed": false,
      "variantKey": "400",
      "suffix": "400x400",
      "width": 400,
      "height": 400,
      "durationMs": 4000
    },
    "aoe": {
      "size": 10,
      "type": "radius"
    }
  },
  {
    "id": "arcane_hand",
    "name": "Arcane Hand",
    "castMode": "self" as SpellCastMode,
    "embersType": "CIRCLE",
    "concentration": false,
    "hasZoneLoop": false,
    "maxTargets": 0,
    "jb2a": {
      "basename": "5th_Level/Arcane_Hand/ArcaneHand_Human_01_Idle_Blue",
      "dpi": 100,
      "directed": false,
      "variantKey": "400",
      "suffix": "400x400",
      "width": 400,
      "height": 400,
      "durationMs": 4096
    }
  },
  {
    "id": "arms_of_hadar",
    "name": "Arms Of Hadar",
    "castMode": "aoe" as SpellCastMode,
    "embersType": "CIRCLE",
    "concentration": false,
    "hasZoneLoop": true,
    "maxTargets": 0,
    "jb2a": {
      "basename": "1st_Level/Arms_Of_Hadar/ArmsOfHadar_01_Dark_Purple",
      "dpi": 500,
      "directed": false,
      "variantKey": "500",
      "suffix": "500x500",
      "width": 500,
      "height": 500,
      "durationMs": 5000
    },
    "aoe": {
      "size": 10,
      "type": "radius"
    }
  },
  {
    "id": "black_tentacles",
    "name": "Black Tentacles",
    "castMode": "aoe" as SpellCastMode,
    "embersType": "CIRCLE",
    "concentration": true,
    "hasZoneLoop": true,
    "maxTargets": 0,
    "jb2a": {
      "basename": "4th_Level/Black_Tentacles/BlackTentacles_01_Dark_Purple",
      "dpi": 200,
      "directed": false,
      "variantKey": "600",
      "suffix": "600x600",
      "width": 600,
      "height": 600,
      "durationMs": 5000
    },
    "aoe": {
      "size": 20,
      "type": "radius"
    }
  },
  {
    "id": "bless",
    "name": "Bless",
    "castMode": "self" as SpellCastMode,
    "embersType": "CIRCLE",
    "concentration": false,
    "hasZoneLoop": false,
    "maxTargets": 0,
    "jb2a": {
      "basename": "1st_Level/Bless/Bless_01_Regular_Yellow_Intro",
      "dpi": 200,
      "directed": false,
      "variantKey": "400",
      "suffix": "400x400",
      "width": 400,
      "height": 400,
      "durationMs": 5000
    }
  },
  {
    "id": "burning_hands",
    "name": "Burning Hands",
    "castMode": "aoe" as SpellCastMode,
    "embersType": "CONE",
    "concentration": false,
    "hasZoneLoop": false,
    "maxTargets": 0,
    "jb2a": {
      "basename": "1st_Level/Burning_Hands/BurningHands_01_Regular_Orange",
      "dpi": 600,
      "directed": true,
      "variantKey": "600",
      "suffix": "600x600",
      "width": 600,
      "height": 600,
      "durationMs": 5570
    },
    "aoe": {
      "size": 15,
      "type": "cone"
    }
  },
  {
    "id": "call_lightning",
    "name": "Call Lightning",
    "castMode": "aoe" as SpellCastMode,
    "embersType": "CIRCLE",
    "concentration": true,
    "hasZoneLoop": true,
    "maxTargets": 0,
    "jb2a": {
      "basename": "3rd_Level/Call_Lightning/CallLightning_01_Blue",
      "dpi": 200,
      "directed": false,
      "variantKey": "1000",
      "suffix": "1000x1000",
      "width": 1000,
      "height": 1000,
      "durationMs": 4000
    },
    "aoe": {
      "size": 60,
      "type": "radius"
    }
  },
  {
    "id": "chain_lightning",
    "name": "Chain Lightning",
    "castMode": "ranged" as SpellCastMode,
    "embersType": "TARGET",
    "concentration": false,
    "hasZoneLoop": false,
    "maxTargets": 4,
    "jb2a": {
      "basename": "6th_Level/Chain_Lightning/ChainLightning_01_Regular_Blue",
      "dpi": 200,
      "directed": true,
      "variantKey": "1200",
      "suffix": "30ft_Primary_1600x400",
      "width": 1600,
      "height": 400,
      "durationMs": 1700
    }
  },
  {
    "id": "cloud_of_daggers",
    "name": "Cloud Of Daggers",
    "castMode": "aoe" as SpellCastMode,
    "embersType": "CIRCLE",
    "concentration": true,
    "hasZoneLoop": true,
    "maxTargets": 0,
    "jb2a": {
      "basename": "2nd_Level/Cloud_Of_Daggers/CloudOfDaggers_01_Light_Blue",
      "dpi": 100,
      "directed": false,
      "variantKey": "400",
      "suffix": "400x400",
      "width": 400,
      "height": 400,
      "durationMs": 5000
    },
    "aoe": {
      "size": 5,
      "type": "radius"
    }
  },
  {
    "id": "cone_of_cold",
    "name": "Cone Of Cold",
    "castMode": "aoe" as SpellCastMode,
    "embersType": "CONE",
    "concentration": false,
    "hasZoneLoop": false,
    "maxTargets": 0,
    "jb2a": {
      "basename": "5th_Level/Cone_Of_Cold/ConeOfCold_01_Regular_Blue",
      "dpi": 200,
      "directed": true,
      "variantKey": "600",
      "suffix": "600x600",
      "width": 600,
      "height": 600,
      "durationMs": 4400
    },
    "aoe": {
      "size": 60,
      "type": "cone"
    }
  },
  {
    "id": "cure_wounds",
    "name": "Cure Wounds",
    "castMode": "melee" as SpellCastMode,
    "embersType": "CIRCLE",
    "concentration": false,
    "hasZoneLoop": false,
    "maxTargets": 1,
    "jb2a": {
      "basename": "1st_Level/Cure_Wounds/CureWounds_01_Blue",
      "dpi": 200,
      "directed": false,
      "variantKey": "400",
      "suffix": "400x400",
      "width": 400,
      "height": 400,
      "durationMs": 2470
    }
  },
  {
    "id": "dancing_lights",
    "name": "Dancing Lights",
    "castMode": "self" as SpellCastMode,
    "embersType": "CIRCLE",
    "concentration": false,
    "hasZoneLoop": false,
    "maxTargets": 0,
    "jb2a": {
      "basename": "Cantrip/Dancing_Lights/DancingLights_01_BlueTeal",
      "dpi": 200,
      "directed": false,
      "variantKey": "200",
      "suffix": "200x200",
      "width": 200,
      "height": 200,
      "durationMs": 4000
    }
  },
  {
    "id": "darkness",
    "name": "Darkness",
    "castMode": "aoe" as SpellCastMode,
    "embersType": "CIRCLE",
    "concentration": true,
    "hasZoneLoop": true,
    "maxTargets": 0,
    "jb2a": {
      "basename": "2nd_Level/Darkness/Darkness_01_Black",
      "dpi": 200,
      "directed": false,
      "variantKey": "600",
      "suffix": "600x600",
      "width": 600,
      "height": 600,
      "durationMs": 5000
    },
    "aoe": {
      "size": 15,
      "type": "radius"
    }
  },
  {
    "id": "detect_magic",
    "name": "Detect Magic",
    "castMode": "self" as SpellCastMode,
    "embersType": "CIRCLE",
    "concentration": true,
    "hasZoneLoop": true,
    "maxTargets": 0,
    "jb2a": {
      "basename": "1st_Level/Detect_Magic/DetectMagicCircle_01_Regular_Blue",
      "dpi": 200,
      "directed": false,
      "variantKey": "1200",
      "suffix": "1200x1200",
      "width": 1200,
      "height": 1200,
      "durationMs": 4003
    },
    "aoe": {
      "size": 30,
      "type": "radius"
    }
  },
  {
    "id": "disintegrate",
    "name": "Disintegrate",
    "castMode": "ranged" as SpellCastMode,
    "embersType": "TARGET",
    "concentration": false,
    "hasZoneLoop": false,
    "maxTargets": 1,
    "jb2a": {
      "basename": "6th_Level/Disintegrate/Disintegrate_01_Regular_Green01",
      "dpi": 200,
      "directed": true,
      "variantKey": "1800",
      "suffix": "45ft_2200x400",
      "width": 2200,
      "height": 400,
      "durationMs": 3030
    }
  },
  {
    "id": "divine_smite",
    "name": "Divine Smite",
    "castMode": "melee" as SpellCastMode,
    "embersType": "CIRCLE",
    "concentration": false,
    "hasZoneLoop": false,
    "maxTargets": 1,
    "jb2a": {
      "basename": "2nd_Level/Divine_Smite/DivineSmite_01_Regular_BlueYellow_Caster",
      "dpi": 100,
      "directed": false,
      "variantKey": "400",
      "suffix": "400x400",
      "width": 400,
      "height": 400,
      "durationMs": 3030
    }
  },
  {
    "id": "eldritch_blast",
    "name": "Eldritch Blast",
    "castMode": "ranged" as SpellCastMode,
    "embersType": "TARGET",
    "concentration": false,
    "hasZoneLoop": false,
    "maxTargets": 1,
    "jb2a": {
      "basename": "Cantrip/Eldritch_Blast/EldritchBlast_01_Regular_Purple",
      "dpi": 200,
      "directed": true,
      "variantKey": "1200",
      "suffix": "30ft_1600x400",
      "width": 1600,
      "height": 400,
      "durationMs": 4370
    }
  },
  {
    "id": "entangle",
    "name": "Entangle",
    "castMode": "aoe" as SpellCastMode,
    "embersType": "CIRCLE",
    "concentration": true,
    "hasZoneLoop": true,
    "maxTargets": 0,
    "jb2a": {
      "basename": "1st_Level/Entangle/Entangle02_02_Regular_Green",
      "dpi": 100,
      "directed": false,
      "variantKey": "500",
      "suffix": "500x500",
      "width": 500,
      "height": 500,
      "durationMs": 8330
    },
    "aoe": {
      "size": 20,
      "type": "radius"
    }
  },
  {
    "id": "fire_bolt",
    "name": "Fire Bolt",
    "castMode": "ranged" as SpellCastMode,
    "embersType": "TARGET",
    "concentration": false,
    "hasZoneLoop": false,
    "maxTargets": 1,
    "jb2a": {
      "basename": "Cantrip/Fire_Bolt/FireBolt_01_Regular_Orange",
      "dpi": 200,
      "directed": true,
      "variantKey": "1200",
      "suffix": "30ft_1600x400",
      "width": 1600,
      "height": 400,
      "durationMs": 1530
    }
  },
  {
    "id": "fireball",
    "name": "Fireball",
    "castMode": "aoe" as SpellCastMode,
    "embersType": "TARGET",
    "concentration": false,
    "hasZoneLoop": false,
    "maxTargets": 0,
    "jb2a": {
      "basename": "3rd_Level/Fireball/FireballBeam_01_Orange",
      "dpi": 200,
      "directed": true,
      "variantKey": "1200",
      "suffix": "30ft_1600x400",
      "width": 1600,
      "height": 400,
      "durationMs": 4040
    },
    "aoe": {
      "size": 20,
      "type": "radius"
    }
  },
  {
    "id": "flaming_sphere",
    "name": "Flaming Sphere",
    "castMode": "aoe" as SpellCastMode,
    "embersType": "CIRCLE",
    "concentration": true,
    "hasZoneLoop": true,
    "maxTargets": 0,
    "jb2a": {
      "basename": "2nd_Level/Flaming_Sphere/FlamingSphere_01_Blue",
      "dpi": 100,
      "directed": false,
      "variantKey": "200",
      "suffix": "200x200",
      "width": 200,
      "height": 200,
      "durationMs": 5040
    },
    "aoe": {
      "size": 10,
      "type": "radius"
    }
  },
  {
    "id": "fog_cloud",
    "name": "Fog Cloud",
    "castMode": "aoe" as SpellCastMode,
    "embersType": "CIRCLE",
    "concentration": true,
    "hasZoneLoop": true,
    "maxTargets": 0,
    "jb2a": {
      "basename": "1st_Level/Fog_Cloud/FogCloud_01_White",
      "dpi": 200,
      "directed": false,
      "variantKey": "800",
      "suffix": "800x800",
      "width": 800,
      "height": 800,
      "durationMs": 5040
    },
    "aoe": {
      "size": 20,
      "type": "radius"
    }
  },
  {
    "id": "grease",
    "name": "Grease",
    "castMode": "aoe" as SpellCastMode,
    "embersType": "CIRCLE",
    "concentration": false,
    "hasZoneLoop": true,
    "maxTargets": 0,
    "jb2a": {
      "basename": "1st_Level/Grease/Grease_Dark_Brown",
      "dpi": 200,
      "directed": false,
      "variantKey": "600",
      "suffix": "600x600",
      "width": 600,
      "height": 600,
      "durationMs": 10030
    },
    "aoe": {
      "size": 10,
      "type": "radius"
    }
  },
  {
    "id": "guiding_bolt",
    "name": "Guiding Bolt",
    "castMode": "ranged" as SpellCastMode,
    "embersType": "TARGET",
    "concentration": false,
    "hasZoneLoop": false,
    "maxTargets": 1,
    "jb2a": {
      "basename": "1st_Level/Guiding_Bolt/GuidingBolt_01_Regular_BlueYellow",
      "dpi": 200,
      "directed": true,
      "variantKey": "1200",
      "suffix": "30ft_1600x400",
      "width": 1600,
      "height": 400,
      "durationMs": 5900
    }
  },
  {
    "id": "gust_of_wind",
    "name": "Gust Of Wind",
    "castMode": "aoe" as SpellCastMode,
    "embersType": "CONE",
    "concentration": false,
    "hasZoneLoop": false,
    "maxTargets": 0,
    "jb2a": {
      "basename": "2nd_Level/Gust_Of_Wind/GustOfWind_01_White",
      "dpi": 200,
      "directed": true,
      "variantKey": "1200",
      "suffix": "1200x200",
      "width": 1200,
      "height": 200,
      "durationMs": 4030
    },
    "aoe": {
      "size": 60,
      "type": "line"
    }
  },
  {
    "id": "hunters_mark",
    "name": "Hunters Mark",
    "castMode": "self" as SpellCastMode,
    "embersType": "CIRCLE",
    "concentration": true,
    "hasZoneLoop": false,
    "maxTargets": 0,
    "jb2a": {
      "basename": "1st_Level/Hunters_Mark/HuntersMark_01_Regular_Green_Pulse",
      "dpi": 200,
      "directed": false,
      "variantKey": "200",
      "suffix": "200x200",
      "width": 200,
      "height": 200,
      "durationMs": 5000
    }
  },
  {
    "id": "lightning_bolt",
    "name": "Lightning Bolt",
    "castMode": "aoe" as SpellCastMode,
    "embersType": "CONE",
    "concentration": false,
    "hasZoneLoop": false,
    "maxTargets": 0,
    "jb2a": {
      "basename": "3rd_Level/Lightning_Bolt/LightningBolt_01_Regular_Blue",
      "dpi": 200,
      "directed": true,
      "variantKey": "4000",
      "suffix": "4000x200",
      "width": 4000,
      "height": 200,
      "durationMs": 4000
    },
    "aoe": {
      "size": 100,
      "type": "line"
    }
  },
  {
    "id": "magic_missile",
    "name": "Magic Missile",
    "castMode": "ranged" as SpellCastMode,
    "embersType": "TARGET",
    "concentration": false,
    "hasZoneLoop": false,
    "maxTargets": 3,
    "jb2a": {
      "basename": "1st_Level/Magic_Missile/MagicMissile_01_Regular_Purple",
      "dpi": 200,
      "directed": true,
      "variantKey": "1200",
      "suffix": "30ft_01_1600x400",
      "width": 1600,
      "height": 400,
      "durationMs": 1870
    }
  },
  {
    "id": "misty_step",
    "name": "Misty Step",
    "castMode": "self" as SpellCastMode,
    "embersType": "CIRCLE",
    "concentration": false,
    "hasZoneLoop": false,
    "maxTargets": 0,
    "jb2a": {
      "basename": "2nd_Level/Misty_Step/MistyStep_01_Regular_Blue",
      "dpi": 100,
      "directed": false,
      "variantKey": "400",
      "suffix": "400x400",
      "width": 400,
      "height": 400,
      "durationMs": 3000
    }
  },
  {
    "id": "moonbeam",
    "name": "Moonbeam",
    "castMode": "aoe" as SpellCastMode,
    "embersType": "CIRCLE",
    "concentration": true,
    "hasZoneLoop": true,
    "maxTargets": 0,
    "jb2a": {
      "basename": "2nd_Level/Moonbeam/Moonbeam_01_Regular_Blue",
      "dpi": 100,
      "directed": false,
      "variantKey": "400",
      "suffix": "400x400",
      "width": 400,
      "height": 400,
      "durationMs": 5040
    },
    "aoe": {
      "size": 5,
      "type": "radius"
    }
  },
  {
    "id": "ray_of_frost",
    "name": "Ray Of Frost",
    "castMode": "ranged" as SpellCastMode,
    "embersType": "TARGET",
    "concentration": false,
    "hasZoneLoop": false,
    "maxTargets": 1,
    "jb2a": {
      "basename": "Cantrip/Ray_Of_Frost/RayOfFrost_01_Regular_Blue",
      "dpi": 200,
      "directed": true,
      "variantKey": "1200",
      "suffix": "30ft_1600x400",
      "width": 1600,
      "height": 400,
      "durationMs": 2530
    }
  },
  {
    "id": "sacred_flame",
    "name": "Sacred Flame",
    "castMode": "self" as SpellCastMode,
    "embersType": "CIRCLE",
    "concentration": false,
    "hasZoneLoop": false,
    "maxTargets": 0,
    "jb2a": {
      "basename": "Cantrip/Sacred_Flame/SacredFlameSource_01_Regular_Yellow",
      "dpi": 400,
      "directed": false,
      "variantKey": "400",
      "suffix": "400x400",
      "width": 400,
      "height": 400,
      "durationMs": 4500
    }
  },
  {
    "id": "scorching_ray",
    "name": "Scorching Ray",
    "castMode": "ranged" as SpellCastMode,
    "embersType": "TARGET",
    "concentration": false,
    "hasZoneLoop": false,
    "maxTargets": 3,
    "jb2a": {
      "basename": "2nd_Level/Scorching_Ray/ScorchingRay_01_Regular_Orange",
      "dpi": 200,
      "directed": true,
      "variantKey": "1200",
      "suffix": "30ft_1600x400",
      "width": 1600,
      "height": 400,
      "durationMs": 1800
    }
  },
  {
    "id": "shatter",
    "name": "Shatter",
    "castMode": "aoe" as SpellCastMode,
    "embersType": "CIRCLE",
    "concentration": false,
    "hasZoneLoop": false,
    "maxTargets": 0,
    "jb2a": {
      "basename": "2nd_Level/Shatter/Shatter_01_Blue",
      "dpi": 100,
      "directed": false,
      "variantKey": "400",
      "suffix": "400x400",
      "width": 400,
      "height": 400,
      "durationMs": 3030
    },
    "aoe": {
      "size": 10,
      "type": "radius"
    }
  },
  {
    "id": "shield",
    "name": "Shield",
    "castMode": "self" as SpellCastMode,
    "embersType": "CIRCLE",
    "concentration": false,
    "hasZoneLoop": false,
    "maxTargets": 0,
    "jb2a": {
      "basename": "1st_Level/Shield/Shield_01_Regular_Blue_Complete",
      "dpi": 200,
      "directed": false,
      "variantKey": "400",
      "suffix": "400x400",
      "width": 400,
      "height": 400,
      "durationMs": 5930
    }
  },
  {
    "id": "sleep",
    "name": "Sleep",
    "castMode": "aoe" as SpellCastMode,
    "embersType": "CIRCLE",
    "concentration": false,
    "hasZoneLoop": false,
    "maxTargets": 0,
    "jb2a": {
      "basename": "1st_Level/Sleep/SleepSymbol01_01_Dark_Pink",
      "dpi": 100,
      "directed": false,
      "variantKey": "400",
      "suffix": "400x400",
      "width": 400,
      "height": 400,
      "durationMs": 2540
    }
  },
  {
    "id": "sleet_storm",
    "name": "Sleet Storm",
    "castMode": "aoe" as SpellCastMode,
    "embersType": "CIRCLE",
    "concentration": true,
    "hasZoneLoop": true,
    "maxTargets": 0,
    "jb2a": {
      "basename": "3rd_Level/Sleet_Storm/SleetStorm_01_Blue",
      "dpi": 200,
      "directed": false,
      "variantKey": "800",
      "suffix": "800x800",
      "width": 800,
      "height": 800,
      "durationMs": 6250
    },
    "aoe": {
      "size": 40,
      "type": "radius"
    }
  },
  {
    "id": "spirit_guardians",
    "name": "Spirit Guardians",
    "castMode": "aoe" as SpellCastMode,
    "embersType": "CIRCLE",
    "concentration": true,
    "hasZoneLoop": true,
    "maxTargets": 0,
    "jb2a": {
      "basename": "3rd_Level/Spirit_Guardians/SpiritGuardians_01_Light_BlueYellow",
      "dpi": 200,
      "directed": false,
      "variantKey": "600",
      "suffix": "600x600",
      "width": 600,
      "height": 600,
      "durationMs": 6250
    },
    "aoe": {
      "size": 15,
      "type": "radius"
    }
  },
  {
    "id": "spiritual_weapon",
    "name": "Spiritual Weapon",
    "castMode": "self" as SpellCastMode,
    "embersType": "CIRCLE",
    "concentration": false,
    "hasZoneLoop": false,
    "maxTargets": 0,
    "jb2a": {
      "basename": "2nd_Level/Spiritual_Weapon/SpiritualWeapon_Club01_02_Spectral_Green",
      "dpi": 100,
      "directed": false,
      "variantKey": "400",
      "suffix": "400x400",
      "width": 400,
      "height": 400,
      "durationMs": 5040
    }
  },
  {
    "id": "thunderwave",
    "name": "Thunderwave",
    "castMode": "aoe" as SpellCastMode,
    "embersType": "CIRCLE",
    "concentration": false,
    "hasZoneLoop": false,
    "maxTargets": 0,
    "jb2a": {
      "basename": "1st_Level/Thunderwave/Thunderwave_01_Bright_Blue_Center",
      "dpi": 200,
      "directed": false,
      "variantKey": "600",
      "suffix": "600x600",
      "width": 600,
      "height": 600,
      "durationMs": 1030
    },
    "aoe": {
      "size": 15,
      "type": "cube"
    }
  },
  {
    "id": "toll_the_dead",
    "name": "Toll The Dead",
    "castMode": "self" as SpellCastMode,
    "embersType": "CIRCLE",
    "concentration": false,
    "hasZoneLoop": false,
    "maxTargets": 0,
    "jb2a": {
      "basename": "Cantrip/Toll_The_Dead/TollTheDead_01_Regular_Green",
      "dpi": 400,
      "directed": false,
      "variantKey": "400",
      "suffix": "400x400",
      "width": 400,
      "height": 400,
      "durationMs": 3530
    }
  },
  {
    "id": "wall_of_fire",
    "name": "Wall Of Fire",
    "castMode": "aoe" as SpellCastMode,
    "embersType": "WALL",
    "concentration": true,
    "hasZoneLoop": true,
    "maxTargets": 0,
    "jb2a": {
      "basename": "4th_Level/Wall_Of_Fire/WallOfFire_01_Blue",
      "dpi": 100,
      "directed": true,
      "variantKey": "300",
      "suffix": "300x100",
      "width": 300,
      "height": 100,
      "durationMs": 4000
    },
    "aoe": {
      "size": 60,
      "type": "line"
    }
  },
  {
    "id": "wall_of_force",
    "name": "Wall Of Force",
    "castMode": "aoe" as SpellCastMode,
    "embersType": "CIRCLE",
    "concentration": false,
    "hasZoneLoop": true,
    "maxTargets": 0,
    "jb2a": {
      "basename": "5th_Level/Wall_Of_Force/WallOfForce_01_Grey_H",
      "dpi": 100,
      "directed": false,
      "variantKey": "200",
      "suffix": "200x200",
      "width": 200,
      "height": 200,
      "durationMs": 4040
    },
    "aoe": {
      "size": 10,
      "type": "cube"
    }
  },
  {
    "id": "web",
    "name": "Web",
    "castMode": "aoe" as SpellCastMode,
    "embersType": "CIRCLE",
    "concentration": true,
    "hasZoneLoop": true,
    "maxTargets": 0,
    "jb2a": {
      "basename": "2nd_Level/Web/Web_01_White_01",
      "dpi": 100,
      "directed": false,
      "variantKey": "400",
      "suffix": "400x400",
      "width": 400,
      "height": 400,
      "durationMs": 5040
    },
    "aoe": {
      "size": 20,
      "type": "radius"
    }
  },
  {
    "id": "whirlwind",
    "name": "Whirlwind",
    "castMode": "aoe" as SpellCastMode,
    "embersType": "CIRCLE",
    "concentration": false,
    "hasZoneLoop": true,
    "maxTargets": 0,
    "jb2a": {
      "basename": "7th_Level/Whirlwind/Whirlwind_01_BlueGrey_01",
      "dpi": 100,
      "directed": false,
      "variantKey": "400",
      "suffix": "400x400",
      "width": 400,
      "height": 400,
      "durationMs": 8040
    },
    "aoe": {
      "size": 30,
      "type": "radius"
    }
  },
  {
    "id": "wind_wall",
    "name": "Wind Wall",
    "castMode": "aoe" as SpellCastMode,
    "embersType": "WALL",
    "concentration": true,
    "hasZoneLoop": true,
    "maxTargets": 0,
    "jb2a": {
      "basename": "3rd_Level/Wind_Wall/WindWall_01_75OPA",
      "dpi": 100,
      "directed": true,
      "variantKey": "300",
      "suffix": "300x100",
      "width": 300,
      "height": 100,
      "durationMs": 4000
    },
    "aoe": {
      "size": 50,
      "type": "line"
    }
  },
  {
    "id": "witch_bolt",
    "name": "Witch Bolt",
    "castMode": "ranged" as SpellCastMode,
    "embersType": "TARGET",
    "concentration": true,
    "hasZoneLoop": false,
    "maxTargets": 1,
    "jb2a": {
      "basename": "1st_Level/Witch_Bolt/WitchBolt_01_Regular_Blue",
      "dpi": 200,
      "directed": true,
      "variantKey": "1200",
      "suffix": "30ft_1600x400",
      "width": 1600,
      "height": 400,
      "durationMs": 4000
    }
  }
];

export const SPELL_EFFECTS_BY_ID = Object.fromEntries(
  SPELL_EFFECTS_CATALOG.map((e) => [e.id, e]),
) as Record<string, SpellEffectCatalogEntry>;

export const SPELL_EFFECTS_BY_NAME = Object.fromEntries(
  SPELL_EFFECTS_CATALOG.map((e) => [e.name.toLowerCase(), e]),
) as Record<string, SpellEffectCatalogEntry>;

export function findSpellEffectCatalogEntry(spellName: string): SpellEffectCatalogEntry | undefined {
  const key = spellName.trim().toLowerCase().replace(/\s+/g, ' ');
  if (SPELL_EFFECTS_BY_NAME[key]) return SPELL_EFFECTS_BY_NAME[key];
  const id = key.replace(/\s+/g, '_');
  return SPELL_EFFECTS_BY_ID[id];
}

export function effectShowsMapZone(effect: ActiveSpellEffect): boolean {
  const catalog = findSpellEffectCatalogEntry(effect.spellName);
  if (!catalog) return false;
  return catalog.hasZoneLoop || catalog.concentration;
}

export function catalogEntryToJb2aAsset(entry: SpellEffectCatalogEntry): Jb2aEffectAsset {
  const { basename, dpi, directed, suffix, width, height, variantKey } = entry.jb2a;
  return {
    basename,
    dpi,
    ...(directed ? { directed: true } : {}),
    variants: {
      [variantKey]: { suffix, width, height, durationMs: entry.jb2a.durationMs },
    },
  };
}
